- package.json
- src/pages/Home/Home.js
- yarn.lock
> FP30 - 在首頁增加一個黑!

- src/components/Navbar.js
> (測試) FP31 - 在 Navbar 增加一個新的分類

- public/index.html
- src/components/Footer.js
- src/components/Navbar.js
- src/constants/globalStyle.js
- src/constants/style.js
- src/index.js
新增 global style、添加共用樣式 & 調整 navbar / footer ~
> FP-44 Constants 共用樣式

- src/components/Modal.js
- src/components/admin/orderManage/Buttons.js
- src/components/admin/orderManage/DetailItem.js
- src/components/admin/orderManage/OrderInfo.js
- src/components/admin/orderManage/Search.js
- src/hooks/useFetchData.js
- src/pages/AdminPages/AdminOrders/AdminOrderDetail.js
- src/pages/AdminPages/AdminOrders/AdminOrders.js
- 補上搜尋功能
- 加上 Loading 畫面
- AdminOrderDetail 頁面拆分
待討論：
FullModal  加上 position props 以使用 inline style 調整定位
> FP-63 搜尋功能 & Loading 畫面 & 詳細頁面拆分

- src/components/admin/orderManage/DetailItem.js
- src/components/cartSystem/CartItem.js
> 修正：購物車及訂單管理圖片調整

- src/pages/AdminPages/Layout.js
1. 修正後台身分驗證顯示，避免未登入還是打查詢訂單的API
2. 刪減一個 Nav
3. 調整 footer 高度
> issue Admin layout

- src/App.js
- src/components/Modal.js
- src/components/admin/AdminIsLoading.js
- src/components/admin/orderManage/Buttons.js
- src/components/admin/productManage/AdminAddForms/DescForm.js
- src/components/admin/productManage/AdminAddForms/InfoForm.js
- src/components/admin/productManage/AdminDetailForms/DescForm.js
- src/components/admin/productManage/AdminDetailForms/InfoForm.js
- src/components/productSystem/ProductCard.js
- src/components/productSystem/ProductImg.js
- src/components/productSystem/ProductUpInfo.js
- src/hooks/useCreateProduct.js
- src/pages/AdminPages/Layout.js
- src/pages/AdminPages/Navbar.js
此次完成 : 
1. 後台 loading component & modal component position
2. 前台 add cart item function 沒有傳入圖片問題已解決
待完成 : 
1. 後台 input 輸入字數限制
2. 其他微調
> FP 64 & 65 功能修正與細節版面微調

- src/constants/globalStyle.js
> 修正：加回消失的字體

- src/components/Modal.js
- src/components/admin/orderManage/Buttons.js
- src/pages/AdminPages/AdminOrders/AdminOrderDetail.js
> FP-88 修正後台 Modal

- src/components/Modal.js
> FP-88 移除註解

- src/components/checkoutSystem/step1CartItem.js
- src/components/checkoutSystem/step3OrderItem.js
- src/pages/AdminPages/AdminMembers/AdminMembers.js
- src/pages/InfoPages/Join/Join.js
1. 「加入我們」頁面優化載入速度，將圖片改放在 public   裡面
2. 補齊加入我們資料 
3.拿掉遺漏的 console.log
4. 調整後台會員管理搜尋框位置
5. 變更訂單完成頁商品圖抓取條件
> FP-81 加入我們內容補齊

- src/components/cartSystem/CartMenu.js
- src/components/navbar/Navbar.js
- src/constants/globalStyle.js
> FP-91 測試：修正 mobile 購物車卡片捲軸問題

- src/components/cartSystem/CartMenu.js
- src/components/navbar/MenuStyles.js
- src/constants/globalStyle.js
> FP-91 測試 2：修正 mobile 購物車卡片捲軸問題

- src/components/cartSystem/CartMenu.js
- src/components/navbar/MenuStyles.js
- src/constants/globalStyle.js
Reverts jackielin7789978/DAYEAYEAYEA-frontend#57
桌面版 navbar menu 邊框消失，先退版。
> Revert "FP-91 測試 2：修正 mobile 購物車卡片捲軸問題"

- src/components/cartSystem/CartMenu.js
- src/components/navbar/Navbar.js
- src/constants/globalStyle.js
Reverts jackielin7789978/DAYEAYEAYEA-frontend#56
桌面版 navbar menu 邊框消失，先退版。
> Revert "FP-91 測試：修正 mobile 購物車卡片捲軸問題"

- src/App.js
- src/utils.js
- src/webAPI/adminAPIs.js
> FP-82 JWT時間驗證

- src/components/productSystem/ProductImg.js
將前台商品頁面小圖 styled-component 從 img 修正為 div
> FP-84 微調前台圖片顯示方式

- package.json
- src/App.js
- src/components/Tab.js
- src/components/checkoutSystem/Step.js
- src/components/loginSystem/SignUpForm.js
- src/pages/Checkout/Step2/Step2.js
- src/pages/Login/Login.js
- src/pages/MemberPages/MeTab/MeTab.js
- src/webAPI/loginAPI.js
- yarn.lock
1. 地址驗證，自動帶入客人地址
2. key 名稱優化
3. 拿掉短運算
4. 密碼條件改為英文大小寫皆可
5. 結帳 step2 改打 getMe API 來拿會員資料(原本從 token 拿，但會沒有即時更新)
> FP78 & FP83 地址帶入功能 & 註冊密碼條件修改

- src/App.js
- src/pages/AdminPages/AdminProducts/AdminProducts.js
- src/pages/AdminPages/Navbar.js
1. 調整 route, 能正確的active navbar
>  FP-89 優化後台Navbar顯示

- src/components/admin/TableStyle.js
- src/components/admin/memberManage/MemberItem.js
- src/components/admin/productManage/Table.js
- src/pages/AdminPages/AdminMembers/AdminMembers.js
- src/pages/AdminPages/AdminOrders/AdminOrderDetail.js
- src/pages/AdminPages/AdminOrders/AdminOrders.js
- src/pages/AdminPages/AdminProducts/AdminProducts.js
1. 統一後台介面
2. 修正 adminOrders Paginator key，在 index 前加上 prefix
> FP-96 修正：統一後台頁面樣式

- src/components/admin/orderManage/DetailItem.js
- src/components/cartSystem/CartItem.js
- src/components/general.js
- src/pages/AdminPages/AdminOrders/AdminOrderDetail.js
- src/utils.js
1. 改變訂單狀態後不重打 API，直接透過 state 改變 UI，解決 `location.reload()` 畫面重載問題
2. 順便移除 general.js 中用不到的 ImgAnchor
> 優化：後台訂單管理頁面刷新

- src/components/admin/orderManage/Table.js
- src/pages/AdminPages/AdminOrders/AdminOrders.js
修正以下問題：
1. 後台分頁顯示 NaN
2. 封存訂單筆數、頁數會受 filter 和目前頁數干擾
3. 移除沒使用到的 props
> fix: 修正後台訂單分頁問題

- README.md
> FP-76 微調 README

- src/App.js
- src/components/Modal.js
- src/components/admin/AdminIsLoading.js
- src/components/productSystem/ProductCard.js
- src/components/productSystem/ProductUpInfo.js
- src/context.js
- src/pages/AdminPages/Layout.js
- src/pages/AdminPages/Navbar.js
本次修正如下:
1. 新增 NavClickContext 並移至 Layout.js
2. 從 app.js & context.js 移除 ModalContext & LoadingContext 
3. 微調前台加入購物車行為
> FP99 - 改用 useModal & useFetch

- package.json
remove homepage from package.js for netlify deployment
> Netlify 部署

- src/components/loginSystem/SignInForm.js
- src/components/loginSystem/SignUpForm.js
> Netlify 部署：修正其他引入問題

- src/components/productSystem/ProductUpInfo.js
> Netlify 部署：修正引入問題

- README.md
> FP-76：修改 README

- src/components/loginSystem/SignInForm.js
- src/components/loginSystem/loginCard.js
- src/pages/Login/Login.js
> FP-100 忘記密碼 modal
